import { gql } from '@apollo/client';
import { GetServerSidePropsContext } from 'next';
import { unstable_getServerSession } from 'next-auth';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import createClient from '../../graphql/client';
import styles from '../../styles/Home.module.css';
import { PettyCashDetail, UserPettyCash } from '../../types/pettycash';
import { UserInfo } from '../../types/users';
import dateFormat from '../../utils/dateformat';
import titleCase from '../../utils/titlecase';
import { authOptions } from '../api/auth/[...nextauth]';
